<header class="jumbotron masthead">
  <div class="inner">
    <h1>AutoSquare</h1>
    <p>Gluing Foursquare, Google Latitude and such into one big ball of geodata and ductape.</p>
    <p class="download-info">
      <a href="/Login/Register" class="btn btn-primary btn-large">Register <br /><small>(it'll only take a minuite)</small></a> or
      <a href="/Login" class="btn btn-large">Login <br /><small>(huzzuh!)</small></a>
    </p>
  </div>

