   <!-- Footer
      ================================================== -->
      <footer class="footer">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>A product of too much free time by <a href="http://baggett.me">Matthew B</a>.</p>
      </footer>

    </div><!-- /container -->
    
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script src="<?=$this->baseUrl()?>/js/jquery.js"></script>
    <script src="<?=$this->baseUrl()?>/js/google-code-prettify/prettify.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-transition.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-alert.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-modal.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-dropdown.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-scrollspy.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-tab.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-tooltip.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-popover.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-button.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-collapse.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-carousel.js"></script>
    <script src="<?=$this->baseUrl()?>/js/bootstrap-typeahead.js"></script>
    <script src="<?=$this->baseUrl()?>/js/application.js"></script>
    
    				
<!-- Start Open Web Analytics Tracker -->
<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'http://analytics.fouroneone.us/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', 'abca13504aaa1820fb0edb5aca387858']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);

(function() {
	var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
	owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
	_owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
	var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>
<!-- End Open Web Analytics Code -->
				
		