<div id="nav">
	<ul>
		<li id="current"><a href="/">Home</a></li>
		<?php if(!Zend_Auth::getInstance()->hasIdentity()):?>
		<li><a href="<?=$this->url(array('controller' => 'Login', 'action' => 'index'),null,true);?>">Login</a></li>
		<li><a href="<?=$this->url(array('controller' => 'Login', 'action' => 'register'),null,true);?>">Register</a></li>
		<?php else:?>
		<li><a href="<?=$this->url(array('controller' => 'Login', 'action' => 'logout'),null,true);?>">Logout</a></li>
		<li><a href="<?=$this->url(array('controller' => 'Search', 'action' => 'my-favourites'),null,true);?>">My Favourites</a></li>
		<!-- <li><a href="<?=$this->url(array('controller' => 'Settings', 'action' => 'index'),null,true);?>">Settings</a></li>-->
		<?php endif;?>
		<!-- <li><a href="<?=$this->url(array('controller' => 'Tags', 'action' => 'index'),null,true);?>">Tags</a></li>-->
		<li><a href="<?=$this->url(array('controller' => 'Search', 'action' => 'latest'),null,true);?>">Latest</a></li>
		<li><a href="<?=$this->url(array('controller' => 'Search', 'action' => 'favourited'),null,true);?>">Most Favourited</a></li>
		<li><a href="<?=$this->url(array('controller' => 'Search', 'action' => 'popular'),null,true);?>">Most Popular</a></li>
	</ul>
</div>