<div id="featured">			
	
		<div id="featured-block" class="clear">
			
			<div id="featured-ribbon"></div>	
				
			<a name="TemplateInfo"></a>
			
			<div class="image-block">
              <a href="/" title=""><img src="images/img-featured.jpg" alt="featured" width="350px" height="250px"/></a>
         </div>			
			
			<div class="text-block">
			
				<h2><a href="/">Read me first</a></h2>
			
				<p class="post-info">Posted by <a href="/">erwin</a> | Filed under <a href="/">templates</a>, <a href="/">internet</a></p>
				
				<p><strong>JungleLand 1.0</strong> is a free, W3C-compliant, CSS-based website template
				by <a href="http://www.styleshout.com/">styleshout.com</a>. This work is 
				distributed under the <a rel="license" href="http://creativecommons.org/licenses/by/2.5/">
				Creative Commons Attribution 2.5  License</a>, which means that you are free to 
				use and modify it for any purpose. All I ask is that you give me credit for the design by including a <strong>link back</strong> to
				<a href="http://www.styleshout.com/">my website</a>.
                </p>

                <p>
                You can find more of my free template designs at <a href="http://www.styleshout.com/">my website</a>.
				For premium commercial designs, you can check out
                <a href="http://themeforest.net?ref=ealigam" title="Site Templates">Themeforest.net</a>.
				</p>
				
				<p><a href="/" class="more-link">Read More</a></p>
								
			</div>
		
		</div>		
	
	<!-- /featured -->
	</div>