<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('AutoSquare');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
// Add stylesheets to view
$this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.css','screen');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap-responsive.css','screen');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/docs.css','screen');
$this->headLink()->appendStylesheet($this->baseUrl().'/js/google-code-prettify/prettify.css','screen');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/ie6.css','screen','IE 6');

// Create array for the body's classes.
$arr_body_classes = array();

// Interogate our class from Zend, add them to arr_body_classes
$obj_zend_instance = Zend_Controller_Front::getInstance();
$str_controller 	= strtolower($obj_zend_instance->getRequest()->getControllerName());
$str_module 		= strtolower($obj_zend_instance->getRequest()->getModuleName());
$str_action 		= strtolower($obj_zend_instance->getRequest()->getActionName());
array_push($arr_body_classes, $str_action);
array_push($arr_body_classes, $str_controller);
array_push($arr_body_classes, $str_module);
?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<link rel="shortcut icon" href="/favicon.ico" />
<meta name='viewport' content='width=device-width,minimum-scale=1,maximum-scale=1,user-scalable=no' />
</head>
 <body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- wrap -->
<div id="wrap"><!-- header -->
	<?php include("layout.header.phtml")?>
		
			<?php echo $this->layout()->content; ?>	
			

<?php include("layout.footer.phtml")?>


</body>
</html>
