   <!-- Footer
      ================================================== -->
      <footer class="footer">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>A product of too much free time by <a href="http://baggett.me">Matthew B</a>.</p>
      </footer>

    </div><!-- /container -->
    
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?php echo $this->headScript(); ?>
    				
