    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">AutoSquare</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active">
                <a href="/">Home</a>
              </li>
              <?php if(Zend_Auth::getInstance()->hasIdentity()):?>
              <li class="">
                <a href="/Login/Logout">Logout, <?=Zend_Auth::getInstance()->getIdentity()->strNickname?></a>
              </li>
              <li class="">
                <a href="/Me">My Account</a>
              </li>
              <?php else:?>
              <li class="">
                <a href="/Login">Login</a>
              </li>
              <?php endif;?>
              
              
            </ul>
          </div>
        </div>
      </div>
    </div>