<div id="footer"><!-- footer-outer -->
<div id="footer-outer" class="clear">
<div id="footer-wrap">
 
<div class="col-a">
	
	<h3>Contact Info</h3>
	
	<p><strong>E-mail: </strong> <a href="mailto:boris@bunnehbutt.com">boris@bunnehbutt.com</a></p>
	
	<h3>Follow Us</h3>
	
	<div class="footer-list">
	<ul>
		<li><a href="#" class="rssfeed">RSS Feed</a></li>
		<li><a href="mailto:boris@bunnehbutt.com" class="email">Email</a></li>
		<li><a href="#" class="twitter">Twitter</a></li>
	</ul>
	</div>

</div>

<div class="col-a">
	
	<h3>Popular Searches</h3>
	
	<div class="footer-list">
	<ul>
		<li><a href="#">Tag</a></li>
		<li><a href="#">Tag</a></li>
		<li><a href="#">Tag</a></li>
		<li><a href="#">Tag</a></li>
		<li><a href="#">Tag</a></li>
		<li><a href="#">Tag</a></li>
		<li><a href="#">Tag</a></li>
	</ul>
	</div>

</div>



<div class="col-b">
	<h3>About</h3>
	<p>Bunnehbutt is a indexer. All you see before you is gleaned from other websites, galleries and the web as a whole. Its hard to argue that it shouldn't be here, if its generally available.</p>
	<p>Takedown policy/process coming soon</p>
</div>

<div class="fix"></div>

<!-- footer-bottom -->
<div id="footer-bottom">

<div class="bottom-left">
<p>Code & API &copy; 2009-<?=date("Y")?> <strong>G.E.</strong>; Others
&copy; Various. &nbsp; &nbsp; &nbsp;</p>
</div>

<div class="bottom-right">
<p>
	<a href="mailto:boris@bunnehbutt.com">Problem?</a> | 
	<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> |
	<a href="http://validator.w3.org/check/referer">XHTML</a> | 
	<a href="#">Home</a> | 
	<strong><a href="#top" class="back-to-top">Back to Top</a></strong>
</p>
</div>

<!-- /footer-bottom --></div>

<!-- /footer-outer --></div>
</div>

<!-- /footer --></div>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16302556-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://tracking.turbocrms.com/" : "http://tracking.turbocrms.com/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://tracking.turbocrms.com/piwik.php?idsite=1" style="border:0" alt="" /></p></noscript>
<!-- End Piwik Tracking Code -->
