<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Bunnehbutt');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
// Add stylesheets to view
$this->headLink()->appendStylesheet($this->baseUrl().'/css/screen.css','screen');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/ie6.css','screen','IE 6');

// Add scripts to view
$this->headScript()->appendFile($this->baseUrl()."/js/jquery-1.6.4.min.js");
$this->headScript()->appendFile($this->baseUrl()."/js/jquery.timers.js");
$this->headScript()->appendFile($this->baseUrl()."/js/jquery.appear-1.1.1.min.js");
$this->headScript()->appendFile($this->baseUrl()."/js/bb.js");

//$this->headScript()->appendFile("http://www.bunnehbutt.com:6933/nowjs/now.js");
//$this->headScript()->appendFile($this->baseUrl()."/js/comms.js");

// Create array for the body's classes.
$arr_body_classes = array();

// Interogate our class from Zend, add them to arr_body_classes
$obj_zend_instance = Zend_Controller_Front::getInstance();
$str_controller 	= strtolower($obj_zend_instance->getRequest()->getControllerName());
$str_module 		= strtolower($obj_zend_instance->getRequest()->getModuleName());
$str_action 		= strtolower($obj_zend_instance->getRequest()->getActionName());
array_push($arr_body_classes, $str_action);
array_push($arr_body_classes, $str_controller);
array_push($arr_body_classes, $str_module);
?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<link rel="shortcut icon" href="/favicon.ico" />
<meta name='viewport' content='width=device-width,minimum-scale=1,maximum-scale=1,user-scalable=no' />
</head>
<body class="<?php echo implode(" ",$arr_body_classes);?>">

<!-- wrap -->
<div id="wrap"><!-- header -->
	<?php include("layout.header.phtml")?>
	<?php if($this->featured == true):?>
	<?php include("layout.featured.phtml")?>
	<?php endif;?>
	<!-- content -->
	<div id="content-wrap" class="clear">
		<div id="content"><!-- main -->
			<div id="main" class="<?=$this->nosidebar?'nosidebar':'sidebar'?>">
			<?php echo $this->layout()->content; ?>	
			<div class="fix"></div>
		<!-- /main --></div>
		<?php if($this->nosidebar):?>
		<?php else:?>
			<?php include("layout.sidebar.phtml")?>
		<?php endif;?>
		<!-- /content --></div>
	<!-- /content-wrap --></div>
<!-- /wrap --></div>

<?php include("layout.footer.phtml")?>


</body>
</html>
