
<table class="table table-bordered table-striped">
<thead>
	<tr>
		<?php foreach( $this->arr_locations[0]->toArray() as $key => $column):?>
		<th><?=$key;?></th>
		<?php endforeach;?>
	</tr>
</thead>
<tbody>
	<?php foreach( $this->arr_locations as $location): ?>
	<?php $location = $location->toArray(); ?>
	<tr>
		<?php foreach( $location as $key => $column):?>
		<?php if(strtolower(str_replace(" ","-",$key)) == 'name-of-movement'):?>
			<td class="<?=strtolower(str_replace(" ","-",$key));?>">
				<a href="/Me/View-Movements/left/<?=$location['intUserLocationID']?>/right/<?=$location['intPrevUserLocationID']?>">
					<?=$column;?>
				</a>
			</td>
		<?php else:?>
			<td class="<?=strtolower(str_replace(" ","-",$key));?>">
				<?=$column;?>
			</td>
		<?php endif;?>
		<?php endforeach;?>
	</tr>
	<?php endforeach;?>
</tbody>
</table>