<h2>Data sources</h2>
<ul>
	<li><a href="/Google/Add-Latitude">Google Latitude account.</a></li>
</ul>

<h2>Data sinks</h2>
<ul>
	<li><a href="/Foursquare/Add-Foursquare">Add a Foursquare account.</a></li>
</ul>

<h2>Diagnostics</h2>
<ul>
	<li><a href="/Me/Map">Show a map of my locations</a></li>
	<li><a href="/Me/Show-Session">Show session data.</a></li>
	<li><a href="/Me/Latitude-Get-Location">Get Latitude Location</a></li>
	<?php if(Turbo_Model_User::getCurrentUser()->settingGet("google_latitude_access_token")):?>
		<li class="good">You <b>HAVE</b> got a Google Latitude key. <a href="/Me/My-Keys">Manage your keys.</a></li>
	<?php else:?>
		<li class="bad">You <b>HAVE NOT</b> got a Google Latitude key. <a href="/Google/Add-Latitude">Add one now!</a></li>
	<?php endif;?>
	
	<?php if(Turbo_Model_User::getCurrentUser()->settingGet("foursquare_access_token")):?>
		<li class="good">You <b>HAVE</b> got a Foursquare key.  <a href="/Me/My-Keys">Manage your keys.</a></li>
	<?php else:?>
		<li class="bad">You <b>HAVE NOT</b> got a Foursquare key. <a href="/Foursquare/Add-Foursquare">Add one now!</a></li>
	<?php endif;?>
</ul>

<h2>Backend</h2>
<ul>
	<li><a href="/Google/Update-Location-Feed">Update Location Feed</a></li>
	<li><a href="/Game/Check-For-Achievements">Check for Achievements</a></li>
</ul>